
package org.folio.rest.client;

import io.vertx.core.AsyncResult;
import io.vertx.core.Handler;
import io.vertx.core.buffer.Buffer;
import io.vertx.ext.web.client.HttpResponse;
import io.vertx.ext.web.client.WebClient;
import io.vertx.ext.web.client.WebClientOptions;
import org.folio.rest.tools.utils.VertxUtils;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;


/**
 * Auto-generated code - based on class org.folio.rest.jaxrs.resource.Pubsub
 */
public class PubsubClient {

  private final String tenantId;
  private final String token;
  private final String okapiUrl;
  private final WebClientOptions options;
  private final WebClient httpClient;

  public PubsubClient(String okapiUrl, String tenantId, String token, boolean keepAlive, int connTO, int idleTO) {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    this.tenantId = tenantId;
    this.token = token;
    this.okapiUrl = okapiUrl;
    options = new WebClientOptions();
    options.setLogActivity(true);
    options.setKeepAlive(keepAlive);
    options.setConnectTimeout(connTO);
    options.setIdleTimeout(idleTO);
    httpClient = WebClient.create(VertxUtils.getVertxFromContextOrNew(), options);
  }

  public PubsubClient(String okapiUrl, String tenantId, String token, boolean keepAlive) {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    this(okapiUrl, tenantId, token, keepAlive, 2000, 5000);
  }

  public PubsubClient(String okapiUrl, String tenantId, String token) {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    this(okapiUrl, tenantId, token, true, 2000, 5000);
  }

  /**
   * @deprecated use a constructor that takes a full okapiUrl instead
   */
  @Deprecated
  public PubsubClient(String host, int port, String tenantId, String token, boolean keepAlive, int connTO, int idleTO) {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    this(((("http://" + host) + ":") + port), tenantId, token, keepAlive, connTO, idleTO);
  }

  /**
   * @deprecated use a constructor that takes a full okapiUrl instead
   */
  @Deprecated
  public PubsubClient(String host, int port, String tenantId, String token, boolean keepAlive) {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    this(host, port, tenantId, token, keepAlive, 2000, 5000);
  }

  /**
   * @deprecated use a constructor that takes a full okapiUrl instead
   */
  @Deprecated
  public PubsubClient(String host, int port, String tenantId, String token) {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    this(host, port, tenantId, token, true, 2000, 5000);
  }

  /**
   * Convenience constructor for tests ONLY!<br>Connect to localhost on 8081 as folio_demo tenant.@deprecated  use a constructor that takes a full okapiUrl instead
   */
  @Deprecated
  public PubsubClient() {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    this("localhost", 8081, "folio_demo", "folio_demo", false, 2000, 5000);
  }

  /**
   * Service endpoint "/pubsub/event-types/"+eventTypeName+""+queryParams.toString()
   */
  public void deletePubsubEventTypesByEventTypeName(String eventTypeName, String lang, Handler<AsyncResult<HttpResponse<Buffer>>> responseHandler)
    throws UnsupportedEncodingException {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    StringBuilder queryParams = new StringBuilder("?");
    if (lang != null) {
      queryParams.append("lang=");
      queryParams.append(URLEncoder.encode(lang, "UTF-8"));
      queryParams.append("&");
    }
    io.vertx.ext.web.client.HttpRequest<Buffer> request = httpClient.requestAbs(io.vertx.core.http.HttpMethod.DELETE, okapiUrl + "/pubsub/event-types/" + eventTypeName + "" + queryParams.toString());
    request.putHeader("Accept", "text/plain");
    if (tenantId != null) {
      request.putHeader("X-Okapi-Token", token);
      request.putHeader("x-okapi-tenant", tenantId);
    }
    if (okapiUrl != null) {
      request.putHeader("X-Okapi-Url", okapiUrl);
    }
    request.send(responseHandler);
  }

  /**
   * Service endpoint "/pubsub/event-types/"+eventTypeName+"/publishers"+queryParams.toString()
   */
  public void deletePubsubEventTypesPublishersByEventTypeName(String eventTypeName, String moduleId, Handler<AsyncResult<HttpResponse<Buffer>>> responseHandler)
    throws UnsupportedEncodingException {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    StringBuilder queryParams = new StringBuilder("?");
    if (moduleId != null) {
      queryParams.append("moduleId=");
      queryParams.append(URLEncoder.encode(moduleId, "UTF-8"));
      queryParams.append("&");
    }
    io.vertx.ext.web.client.HttpRequest<Buffer> request = httpClient.requestAbs(io.vertx.core.http.HttpMethod.DELETE, okapiUrl + "/pubsub/event-types/" + eventTypeName + "/publishers" + queryParams.toString());
    if (tenantId != null) {
      request.putHeader("X-Okapi-Token", token);
      request.putHeader("x-okapi-tenant", tenantId);
    }
    if (okapiUrl != null) {
      request.putHeader("X-Okapi-Url", okapiUrl);
    }
    request.send(responseHandler);
  }

  /**
   * Service endpoint "/pubsub/event-types/"+eventTypeName+"/subscribers"+queryParams.toString()
   */
  public void deletePubsubEventTypesSubscribersByEventTypeName(String eventTypeName, String moduleId, Handler<AsyncResult<HttpResponse<Buffer>>> responseHandler)
    throws UnsupportedEncodingException {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    StringBuilder queryParams = new StringBuilder("?");
    if (moduleId != null) {
      queryParams.append("moduleId=");
      queryParams.append(URLEncoder.encode(moduleId, "UTF-8"));
      queryParams.append("&");
    }
    io.vertx.ext.web.client.HttpRequest<Buffer> request = httpClient.requestAbs(io.vertx.core.http.HttpMethod.DELETE, okapiUrl + "/pubsub/event-types/" + eventTypeName + "/subscribers" + queryParams.toString());
    if (tenantId != null) {
      request.putHeader("X-Okapi-Token", token);
      request.putHeader("x-okapi-tenant", tenantId);
    }
    if (okapiUrl != null) {
      request.putHeader("X-Okapi-Url", okapiUrl);
    }
    request.send(responseHandler);
  }

  /**
   * Service endpoint "/pubsub/messaging-modules"+queryParams.toString()
   */
  public void deletePubsubMessagingModules(String moduleId, String moduleRole, Handler<AsyncResult<HttpResponse<Buffer>>> responseHandler)
    throws UnsupportedEncodingException {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    StringBuilder queryParams = new StringBuilder("?");
    if (moduleId != null) {
      queryParams.append("moduleId=");
      queryParams.append(URLEncoder.encode(moduleId, "UTF-8"));
      queryParams.append("&");
    }
    if (moduleRole != null) {
      queryParams.append("moduleRole=");
      queryParams.append(URLEncoder.encode(moduleRole, "UTF-8"));
      queryParams.append("&");
    }
    io.vertx.ext.web.client.HttpRequest<Buffer> request = httpClient.requestAbs(io.vertx.core.http.HttpMethod.DELETE, okapiUrl + "/pubsub/messaging-modules" + queryParams.toString());
    request.putHeader("Accept", "text/plain");
    if (tenantId != null) {
      request.putHeader("X-Okapi-Token", token);
      request.putHeader("x-okapi-tenant", tenantId);
    }
    if (okapiUrl != null) {
      request.putHeader("X-Okapi-Url", okapiUrl);
    }
    request.send(responseHandler);
  }

  /**
   * Service endpoint "/pubsub/audit-messages/"+eventId+"/payload"+queryParams.toString()
   */
  public void getPubsubAuditMessagesPayloadByEventId(String eventId, Handler<AsyncResult<HttpResponse<Buffer>>> responseHandler) {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    StringBuilder queryParams = new StringBuilder("?");
    io.vertx.ext.web.client.HttpRequest<Buffer> request = httpClient.requestAbs(io.vertx.core.http.HttpMethod.GET, okapiUrl + "/pubsub/audit-messages/" + eventId + "/payload" + queryParams.toString());
    request.putHeader("Accept", "application/json,text/plain");
    if (tenantId != null) {
      request.putHeader("X-Okapi-Token", token);
      request.putHeader("x-okapi-tenant", tenantId);
    }
    if (okapiUrl != null) {
      request.putHeader("X-Okapi-Url", okapiUrl);
    }
    request.send(responseHandler);
  }

  /**
   * Service endpoint "/pubsub/event-types"+queryParams.toString()
   */
  public void getPubsubEventTypes(String lang, Handler<AsyncResult<HttpResponse<Buffer>>> responseHandler)
    throws UnsupportedEncodingException {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    StringBuilder queryParams = new StringBuilder("?");
    if (lang != null) {
      queryParams.append("lang=");
      queryParams.append(URLEncoder.encode(lang, "UTF-8"));
      queryParams.append("&");
    }
    io.vertx.ext.web.client.HttpRequest<Buffer> request = httpClient.requestAbs(io.vertx.core.http.HttpMethod.GET, okapiUrl + "/pubsub/event-types" + queryParams.toString());
    request.putHeader("Accept", "application/json,text/plain");
    if (tenantId != null) {
      request.putHeader("X-Okapi-Token", token);
      request.putHeader("x-okapi-tenant", tenantId);
    }
    if (okapiUrl != null) {
      request.putHeader("X-Okapi-Url", okapiUrl);
    }
    request.send(responseHandler);
  }

  /**
   * Service endpoint "/pubsub/event-types/"+eventTypeName+""+queryParams.toString()
   */
  public void getPubsubEventTypesByEventTypeName(String eventTypeName, String lang, Handler<AsyncResult<HttpResponse<Buffer>>> responseHandler)
    throws UnsupportedEncodingException {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    StringBuilder queryParams = new StringBuilder("?");
    if (lang != null) {
      queryParams.append("lang=");
      queryParams.append(URLEncoder.encode(lang, "UTF-8"));
      queryParams.append("&");
    }
    io.vertx.ext.web.client.HttpRequest<Buffer> request = httpClient.requestAbs(io.vertx.core.http.HttpMethod.GET, okapiUrl + "/pubsub/event-types/" + eventTypeName + "" + queryParams.toString());
    request.putHeader("Accept", "application/json,text/plain");
    if (tenantId != null) {
      request.putHeader("X-Okapi-Token", token);
      request.putHeader("x-okapi-tenant", tenantId);
    }
    if (okapiUrl != null) {
      request.putHeader("X-Okapi-Url", okapiUrl);
    }
    request.send(responseHandler);
  }

  /**
   * Service endpoint "/pubsub/event-types/"+eventTypeName+"/publishers"+queryParams.toString()
   */
  public void getPubsubEventTypesPublishersByEventTypeName(String eventTypeName, Handler<AsyncResult<HttpResponse<Buffer>>> responseHandler) {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    StringBuilder queryParams = new StringBuilder("?");
    io.vertx.ext.web.client.HttpRequest<Buffer> request = httpClient.requestAbs(io.vertx.core.http.HttpMethod.GET, okapiUrl + "/pubsub/event-types/" + eventTypeName + "/publishers" + queryParams.toString());
    request.putHeader("Accept", "application/json");
    if (tenantId != null) {
      request.putHeader("X-Okapi-Token", token);
      request.putHeader("x-okapi-tenant", tenantId);
    }
    if (okapiUrl != null) {
      request.putHeader("X-Okapi-Url", okapiUrl);
    }
    request.send(responseHandler);
  }

  /**
   * Service endpoint "/pubsub/event-types/"+eventTypeName+"/subscribers"+queryParams.toString()
   */
  public void getPubsubEventTypesSubscribersByEventTypeName(String eventTypeName, Handler<AsyncResult<HttpResponse<Buffer>>> responseHandler) {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    StringBuilder queryParams = new StringBuilder("?");
    io.vertx.ext.web.client.HttpRequest<Buffer> request = httpClient.requestAbs(io.vertx.core.http.HttpMethod.GET, okapiUrl + "/pubsub/event-types/" + eventTypeName + "/subscribers" + queryParams.toString());
    request.putHeader("Accept", "application/json");
    if (tenantId != null) {
      request.putHeader("X-Okapi-Token", token);
      request.putHeader("x-okapi-tenant", tenantId);
    }
    if (okapiUrl != null) {
      request.putHeader("X-Okapi-Url", okapiUrl);
    }
    request.send(responseHandler);
  }

  /**
   * Service endpoint "/pubsub/history"+queryParams.toString()
   */
  public void getPubsubHistory(String startDate, String endDate, String eventId, String eventType, String correlationId, Handler<AsyncResult<HttpResponse<Buffer>>> responseHandler)
    throws UnsupportedEncodingException {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    StringBuilder queryParams = new StringBuilder("?");
    if (startDate != null) {
      queryParams.append("startDate=");
      queryParams.append(URLEncoder.encode(startDate, "UTF-8"));
      queryParams.append("&");
    }
    if (endDate != null) {
      queryParams.append("endDate=");
      queryParams.append(URLEncoder.encode(endDate, "UTF-8"));
      queryParams.append("&");
    }
    if (eventId != null) {
      queryParams.append("eventId=");
      queryParams.append(URLEncoder.encode(eventId, "UTF-8"));
      queryParams.append("&");
    }
    if (eventType != null) {
      queryParams.append("eventType=");
      queryParams.append(URLEncoder.encode(eventType, "UTF-8"));
      queryParams.append("&");
    }
    if (correlationId != null) {
      queryParams.append("correlationId=");
      queryParams.append(URLEncoder.encode(correlationId, "UTF-8"));
      queryParams.append("&");
    }
    io.vertx.ext.web.client.HttpRequest<Buffer> request = httpClient.requestAbs(io.vertx.core.http.HttpMethod.GET, okapiUrl + "/pubsub/history" + queryParams.toString());
    request.putHeader("Accept", "application/json,text/plain");
    if (tenantId != null) {
      request.putHeader("X-Okapi-Token", token);
      request.putHeader("x-okapi-tenant", tenantId);
    }
    if (okapiUrl != null) {
      request.putHeader("X-Okapi-Url", okapiUrl);
    }
    request.send(responseHandler);
  }

  /**
   * Service endpoint "/pubsub/event-types"+queryParams.toString()
   */
  public void postPubsubEventTypes(String lang, org.folio.rest.jaxrs.model.EventDescriptor EventDescriptor, Handler<AsyncResult<HttpResponse<Buffer>>> responseHandler)
    throws UnsupportedEncodingException, Exception {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    StringBuilder queryParams = new StringBuilder("?");
    if (lang != null) {
      queryParams.append("lang=");
      queryParams.append(URLEncoder.encode(lang, "UTF-8"));
      queryParams.append("&");
    }
    Buffer buffer = Buffer.buffer();
    if (EventDescriptor != null) {
      buffer.appendString(org.folio.rest.tools.ClientHelpers.pojo2json(EventDescriptor));
    }
    io.vertx.ext.web.client.HttpRequest<Buffer> request = httpClient.requestAbs(io.vertx.core.http.HttpMethod.POST, okapiUrl + "/pubsub/event-types" + queryParams.toString());
    request.putHeader("Content-type", "application/json");
    request.putHeader("Accept", "application/json,text/plain");
    if (tenantId != null) {
      request.putHeader("X-Okapi-Token", token);
      request.putHeader("x-okapi-tenant", tenantId);
    }
    if (okapiUrl != null) {
      request.putHeader("X-Okapi-Url", okapiUrl);
    }
    request.sendBuffer(buffer, responseHandler);
  }

  /**
   * Service endpoint "/pubsub/event-types/declare/publisher"+queryParams.toString()
   */
  public void postPubsubEventTypesDeclarePublisher(org.folio.rest.jaxrs.model.PublisherDescriptor PublisherDescriptor, Handler<AsyncResult<HttpResponse<Buffer>>> responseHandler)
    throws Exception {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    StringBuilder queryParams = new StringBuilder("?");
    Buffer buffer = Buffer.buffer();
    if (PublisherDescriptor != null) {
      buffer.appendString(org.folio.rest.tools.ClientHelpers.pojo2json(PublisherDescriptor));
    }
    io.vertx.ext.web.client.HttpRequest<Buffer> request = httpClient.requestAbs(io.vertx.core.http.HttpMethod.POST, okapiUrl + "/pubsub/event-types/declare/publisher" + queryParams.toString());
    request.putHeader("Content-type", "application/json");
    request.putHeader("Accept", "application/json,text/plain");
    if (tenantId != null) {
      request.putHeader("X-Okapi-Token", token);
      request.putHeader("x-okapi-tenant", tenantId);
    }
    if (okapiUrl != null) {
      request.putHeader("X-Okapi-Url", okapiUrl);
    }
    request.sendBuffer(buffer, responseHandler);
  }

  /**
   * Service endpoint "/pubsub/event-types/declare/subscriber"+queryParams.toString()
   */
  public void postPubsubEventTypesDeclareSubscriber(org.folio.rest.jaxrs.model.SubscriberDescriptor SubscriberDescriptor, Handler<AsyncResult<HttpResponse<Buffer>>> responseHandler)
    throws Exception {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    StringBuilder queryParams = new StringBuilder("?");
    Buffer buffer = Buffer.buffer();
    if (SubscriberDescriptor != null) {
      buffer.appendString(org.folio.rest.tools.ClientHelpers.pojo2json(SubscriberDescriptor));
    }
    io.vertx.ext.web.client.HttpRequest<Buffer> request = httpClient.requestAbs(io.vertx.core.http.HttpMethod.POST, okapiUrl + "/pubsub/event-types/declare/subscriber" + queryParams.toString());
    request.putHeader("Content-type", "application/json");
    request.putHeader("Accept", "application/json,text/plain");
    if (tenantId != null) {
      request.putHeader("X-Okapi-Token", token);
      request.putHeader("x-okapi-tenant", tenantId);
    }
    if (okapiUrl != null) {
      request.putHeader("X-Okapi-Url", okapiUrl);
    }
    request.sendBuffer(buffer, responseHandler);
  }

  /**
   * Service endpoint "/pubsub/publish"+queryParams.toString()
   */
  public void postPubsubPublish(org.folio.rest.jaxrs.model.Event Event, Handler<AsyncResult<HttpResponse<Buffer>>> responseHandler)
    throws Exception {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    StringBuilder queryParams = new StringBuilder("?");
    Buffer buffer = Buffer.buffer();
    if (Event != null) {
      buffer.appendString(org.folio.rest.tools.ClientHelpers.pojo2json(Event));
    }
    io.vertx.ext.web.client.HttpRequest<Buffer> request = httpClient.requestAbs(io.vertx.core.http.HttpMethod.POST, okapiUrl + "/pubsub/publish" + queryParams.toString());
    request.putHeader("Content-type", "application/json");
    request.putHeader("Accept", "application/json,text/plain");
    if (tenantId != null) {
      request.putHeader("X-Okapi-Token", token);
      request.putHeader("x-okapi-tenant", tenantId);
    }
    if (okapiUrl != null) {
      request.putHeader("X-Okapi-Url", okapiUrl);
    }
    request.sendBuffer(buffer, responseHandler);
  }

  /**
   * Service endpoint "/pubsub/event-types/"+eventTypeName+""+queryParams.toString()
   */
  public void putPubsubEventTypesByEventTypeName(String eventTypeName, String lang, org.folio.rest.jaxrs.model.EventDescriptor EventDescriptor, Handler<AsyncResult<HttpResponse<Buffer>>> responseHandler)
    throws UnsupportedEncodingException, Exception {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.PubsubResource
    StringBuilder queryParams = new StringBuilder("?");
    if (lang != null) {
      queryParams.append("lang=");
      queryParams.append(URLEncoder.encode(lang, "UTF-8"));
      queryParams.append("&");
    }
    Buffer buffer = Buffer.buffer();
    if (EventDescriptor != null) {
      buffer.appendString(org.folio.rest.tools.ClientHelpers.pojo2json(EventDescriptor));
    }
    io.vertx.ext.web.client.HttpRequest<Buffer> request = httpClient.requestAbs(io.vertx.core.http.HttpMethod.PUT, okapiUrl + "/pubsub/event-types/" + eventTypeName + "" + queryParams.toString());
    request.putHeader("Content-type", "application/json");
    request.putHeader("Accept", "application/json,text/plain");
    if (tenantId != null) {
      request.putHeader("X-Okapi-Token", token);
      request.putHeader("x-okapi-tenant", tenantId);
    }
    if (okapiUrl != null) {
      request.putHeader("X-Okapi-Url", okapiUrl);
    }
    request.sendBuffer(buffer, responseHandler);
  }

}
