#%RAML 1.0

title: Pub-sub
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: PubSub API
    content: API for event-driven approach

types:
  errors: !include raml-util/schemas/errors.schema
  eventDescriptor: !include eventDescriptor.json
  eventDescriptorCollection: !include eventDescriptorCollection.json
  event: !include event.json
  messagingDescriptor: !include messagingDescriptor.json
  publisherDescriptor: !include publisherDescriptor.json
  subscriberDescriptor: !include subscriberDescriptor.json
  module: !include module.json
  messagingModule: !include messagingModule.json
  messagingModuleCollection: !include messagingModuleCollection.json
  auditMessage: !include auditMessage.json
  auditMessagePayload: !include auditMessagePayload.json
  
traits:
  validate: !include raml-util/traits/validation.raml
  language: !include raml-util/traits/language.raml
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/pubsub:
  /event-types:
    displayName: Event Types
    description: API for managing Event Types
    type:
      collection:
        schemaCollection: eventDescriptorCollection
        schemaItem: eventDescriptor
        exampleCollection: !include examples/eventDescriptorCollection.sample
        exampleItem: !include examples/eventDescriptor.sample
    post:
      description: Create new event type
      is: [validate]
    get:
      description: Get a list of evet types descriptors
    /{eventTypeName}:
      displayName: Event Type
      description: Get, Delete or Update a specific Event Type descriptor
      type:
        collection-item:
          schema: eventDescriptor
          exampleItem: !include examples/eventDescriptor.sample
      put:
        is: [validate]
        responses:
          200:
            body:
              application/json:
                type: eventDescriptor
      delete:
        responses:
          204:
            body:
              text/plain: !!null
      /publishers:
        displayName: Publishers
        description: API for managing Publishers
        get:
          description: API to retrieve registered Publishers
          responses:
            200:
              body:
                application/json:
                  schema: messagingModuleCollection
        delete:
          description: Remove publisher declaration for certain event type
          queryParameters:
            moduleName:
              description: Publisher module name
              required: true
              type: string
          responses:
            204:
              body:
                text/plain: !!null

      /subscribers:
        displayName: Subscribers
        description: API for managing Subscribers
        get:
          description: API to retrieve registered Subscribers
          responses:
            200:
              body:
                application/json:
                  schema: messagingModuleCollection
        delete:
          description:  API to remove Subscriber declaration for certain event type
          queryParameters:
            moduleName:
              description: Subscriber module name
              required: true
              type: string
          responses:
            204:
              body:
                text/plain: !!null
    /declare:
      /publisher:
        displayName: Publishers
        description: API for managing Publishers
        post:
          description: Declare a publisher for a set of event types
          body:
            application/json:
              schema: publisherDescriptor
          responses:
            201:
            400:
              body:
                application/json:
                  schema: errors
            500:
              description: "Internal server error"
              body:
                text/plain:
                  example: "Internal server error"
      /subscriber:
        displayName: Subscribers
        description: Declare a subscriber for a set of event types
        post:
          body:
            application/json:
              schema: subscriberDescriptor
          responses:
            201:
            400:
              body:
                application/json:
                  schema: errors
            500:
              description: "Internal server error"
              body:
                text/plain:
                  example: "Internal server error"
