#%RAML 1.0

title: Pub-sub
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: PubSub API
    content: API for event-driven approach

types:
  errors: !include raml-util/schemas/errors.schema
  eventDescriptor: !include eventDescriptor.json
  event: !include event.json
  messagingDescriptor: !include messagingDescriptor.json
  publisherDescriptor: !include publisherDescriptor.json
  subscriberDescriptor: !include subscriberDescriptor.json

traits:
  validate: !include raml-util/traits/validation.raml
  language: !include raml-util/traits/language.raml
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/pubsub:
  get:
    description: Stub endpoint
    responses:
      200:
